"""Revision to apply initial data

Revision ID: 22c920c77fab
Revises: 21b9881710e4
Create Date: 2023-07-20 23:40:11.971790

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision = "22c920c77fab"
down_revision = "21b9881710e4"
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())
    meta.reflect(
        only=(
            "node",
            "property",
        )
    )
    node = Table("node", meta)
    property = Table("property", meta)

    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        node,
        [
            {"parent_id": None, "name": "ICE"},
            {"parent_id": 1, "name": "Cylinder Block"},
            {"parent_id": 1, "name": "Cylinder Head"},
            {"parent_id": 2, "name": "Cylinder"},
            {"parent_id": 2, "name": "Piston"},
            {"parent_id": 2, "name": "Piston Ring"},
            {"parent_id": 2, "name": "Connecting Rod"},
            {"parent_id": 2, "name": "Crankshaft"},
            {"parent_id": 2, "name": "Cylinder Liner"},
            {"parent_id": 3, "name": "Valves"},
            {"parent_id": 3, "name": "Valve Guides"},
            {"parent_id": 3, "name": "Piston Head"},
            {"parent_id": 3, "name": "Camshaft"},
            {"parent_id": 3, "name": "Thermostat"},
            {"parent_id": 3, "name": "Cylinder Head Gasket"},
            {"parent_id": 4, "name": "Intake Manifold"},
            {"parent_id": 4, "name": "Throttle Valve"},
            {"parent_id": 4, "name": "Fuel Injection"},
            {"parent_id": 4, "name": "Fuel Pump"},
            {"parent_id": 4, "name": "Fuel Filter"},
            {"parent_id": 4, "name": "Fuel Pressure Regulator"},
            {"parent_id": 5, "name": "Ignition System"},
            {"parent_id": 5, "name": "Spark Plugs"},
            {"parent_id": 5, "name": "Distributor"},
            {"parent_id": 5, "name": "Electronic Control Unit (ECU)"},
            {"parent_id": 5, "name": "Ignition Coil"},
            {"parent_id": 6, "name": "Lubrication System"},
            {"parent_id": 6, "name": "Oil Pump"},
            {"parent_id": 6, "name": "Oil Filter"},
            {"parent_id": 6, "name": "Oil Cooler"},
            {"parent_id": 6, "name": "Oil Pan"},
            {"parent_id": 6, "name": "Oil Baffle"},
            {"parent_id": 7, "name": "Cooling System"},
            {"parent_id": 7, "name": "Radiator"},
            {"parent_id": 7, "name": "Fan"},
            {"parent_id": 7, "name": "Thermostat"},
            {"parent_id": 7, "name": "Water Pump"},
            {"parent_id": 7, "name": "Expansion Tank"},
            {"parent_id": 8, "name": "Exhaust System"},
            {"parent_id": 8, "name": "Muffler"},
            {"parent_id": 8, "name": "Catalytic Converter"},
            {"parent_id": 8, "name": "Pipes and Flex Connectors"},
            {"parent_id": 8, "name": "Exhaust Manifold"},
        ],
    )

    op.bulk_insert(
        property,
        [
            {"node_id": 1, "name": "Power", "value": 200.0},
            {"node_id": 1, "name": "Torque", "value": 180.5},
            {"node_id": 2, "name": "Cylinder Count", "value": 4.0},
            {"node_id": 2, "name": "Bore Diameter", "value": 88.0},
            {"node_id": 2, "name": "Stroke Length", "value": 75.0},
            {"node_id": 3, "name": "Intake Valve Diameter", "value": 32.0},
            {"node_id": 3, "name": "Exhaust Valve Diameter", "value": 28.0},
            {"node_id": 4, "name": "Piston Clearance", "value": 0.03},
            {"node_id": 5, "name": "Fuel Injector Flow Rate", "value": 250.0},
            {"node_id": 5, "name": "Throttle Response Time", "value": 0.1},
            {"node_id": 6, "name": "Oil Pressure", "value": 50.0},
            {"node_id": 6, "name": "Oil Temperature", "value": 95.0},
            {"node_id": 7, "name": "Coolant Temperature", "value": 90.0},
            {"node_id": 7, "name": "Radiator Efficiency", "value": 0.85},
            {"node_id": 8, "name": "Exhaust Gas Temperature", "value": 600.0},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM property")
    op.execute("DELETE FROM node")
    # ### end Alembic commands ###
