"""Initial schema

Revision ID: 374e907a0d3f
Revises:
Create Date: 2023-07-19 15:27:05.506284

"""
import sqlalchemy as sa
from alembic import op

from helpers.entity.sql_entity import TZDateTime

# revision identifiers, used by Alembic.
revision = "374e907a0d3f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rocket_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at", TZDateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", TZDateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["rocket_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rocket_node_parent_id"), "rocket_node", ["parent_id"], unique=False
    )
    op.create_table(
        "rocket_property",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rocket_node_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("value", sa.DECIMAL(), nullable=False),
        sa.Column(
            "created_at", TZDateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", TZDateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["rocket_node_id"],
            ["rocket_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rocket_property_rocket_node_id"),
        "rocket_property",
        ["rocket_node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rocket_property_rocket_node_id"), table_name="rocket_property"
    )
    op.drop_table("rocket_property")
    op.drop_index(op.f("ix_rocket_node_parent_id"), table_name="rocket_node")
    op.drop_table("rocket_node")
    # ### end Alembic commands ###
