version: '3.8'

services:

  non-flat-attrs-database:
    image: postgres:15.3
    container_name: non-flat-attrs-database
    restart: always
    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    volumes:
      - non-flat-attrs-database:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=nonflatattrs
      - POSTGRES_USER=markelkaluhin
      - POSTGRES_PASSWORD=myverystrongpassword
      - PGDATA=/var/lib/postgresql/data/pgdata

  be-non-flat-attrs-example:
    image: be-non-flat-attrs-example:latest
    build:
      dockerfile: be/Dockerfile
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    depends_on:
      - non-flat-attrs-database
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - SQLALCHEMY_HOST=non-flat-attrs-database
      - SQLALCHEMY_PORT=5432
      - SQLALCHEMY_USER=markelkaluhin
      - SQLALCHEMY_PASSWORD=myverystrongpassword
      - SQLALCHEMY_DB_NAME=nonflatattrs
      - RELOAD_APP=0
      - ALLOW_ORIGINS=*
      - APPLICATION_NAME=be-non-flat-attrs-example
  fe-non-flat-attrs-example:
    image: fe-non-flat-attrs-example:latest
    build:
      dockerfile: fe/Dockerfile
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    depends_on:
      - be-non-flat-attrs-example

volumes:
  non-flat-attrs-database:
