version: '3.8'

services:

  database:
    image: postgres:15.3
    container_name: database
    restart: always
    ports:
      - 5432:5432
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=myverystrongpassword
      - POSTGRES_USER=markelkaluhin
      - POSTGRES_DB=rocketlab
      - PGDATA=/var/lib/postgresql/data/pgdata

  be-rocket-lab-home-test:
    image: be-rocket-lab-home-test:latest
    build:
      dockerfile: be/Dockerfile
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    depends_on:
      - database
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - SQLALCHEMY_HOST=database
      - SQLALCHEMY_PORT=5432
      - SQLALCHEMY_DB_NAME=rocketlab
      - SQLALCHEMY_USER=markelkaluhin
      - SQLALCHEMY_PASSWORD=myverystrongpassword
      - RELOAD_APP=0
      - ALLOW_ORIGINS=*
      - APPLICATION_NAME=be-rocket-lab-home-test

  fe-rocket-lab-home-test:
    image: fe-rocket-lab-home-test:latest
    build:
      dockerfile: fe/Dockerfile
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: any
      update_config:
        delay: 2s
    depends_on:
      - be-rocket-lab-home-test

volumes:
  postgres:
